#!/bin/bash

FLARECLIENT_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
USAGE="Usage: hashPassword <propertyName> <password>"

# if not 2 args, print usage
if [ $# -ne 2 ]; then
    echo "$USAGE"
    exit 1
else
    PROPERTY=$1
    shift
    PASSWORD=$1
fi

# some Java parameters
if [ "$JAVA_HOME" != "" ]; then
    JAVA_HOME=$JAVA_HOME
fi

if [ "$JAVA_HOME" = "" ]; then
    echo "Error: JAVA_HOME is not set."
    exit 1
fi

JAVA=$JAVA_HOME/bin/java
CLASSPATH="$FLARECLIENT_HOME/lib/log4j-1.2.14.jar:$FLARECLIENT_HOME/lib/flare-client-2.0.jar:$FLARECLIENT_HOME/lib/commons-codec-1.9.jar:$FLARECLIENT_HOME/lib/commons-io-2.4.jar:$FLARECLIENT_HOME"
CLASS=com.bcmcgroup.flare.client.HashPassword

exec "$JAVA" -cp "$CLASSPATH" $CLASS $PROPERTY $PASSWORD
